project:
  type: book
  output-dir: docs

book:
  title: "【非公式】実証ビジネス・エコノミクス Juliaでの実装"
  author: "Mizuhiro Suzuki"
  date: ""
  chapters:
    - index.qmd
    - demand_estimation_1.qmd
    - demand_estimation_2.qmd
    - demand_estimation_merger.qmd
    - entry_exit_basic.qmd
    - entry_exit_application.qmd
    - single_agent_dynamic_basic.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

