project:
  type: book
  output-dir: docs

book:
  title: "【非公式】実証ビジネス・エコノミクス Juliaでの実装"
  author: "Mizuhiro Suzuki"
  date: ""
  chapters:
    - index.qmd
    - part: 消費者需要モデルの推定
      chapters:
        - demand_estimation_1.qmd
        - demand_estimation_2.qmd
        - demand_estimation_merger.qmd
    - part: 参入ゲームの推定
      chapters:
        - entry_exit_basic.qmd
        - entry_exit_application.qmd
    - part: シングルエージェント動学モデルの推定
      chapters:
        - single_agent_dynamic_basic.qmd
        - single_agent_dynamic_application.qmd
    - part: 動学ゲームの推定
      chapters:
        - dynamic_game_data.qmd
        - dynamic_game_estimation_1.qmd
        - dynamic_game_estimation_2.qmd
        - dynamic_game_counterfactual.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

